# Generated by Django 4.1 on 2022-11-04 04:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LINK_ID', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
