# Generated by Django 4.1 on 2022-11-04 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='LINK_ID',
            new_name='link_id',
        ),
    ]
