# Generated by Django 4.0.8 on 2022-11-06 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_joinedlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinedlink',
            name='link_id',
        ),
        migrations.RemoveField(
            model_name='joinedlink',
            name='name',
        ),
    ]
