# Generated by Django 4.0.8 on 2022-11-07 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_joinedlink_link_id_remove_joinedlink_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedlink',
            name='statLV',
            field=models.BigIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marker',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marker',
            name='stat',
            field=models.BigIntegerField(default=2),
            preserve_default=False,
        ),
    ]
