# Generated by Django 4.0.8 on 2022-11-07 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_joinedlink_statlv_marker_date_marker_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='date',
        ),
    ]
