# Generated by Django 4.0.8 on 2022-11-09 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_marker_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinedlink',
            old_name='statLV',
            new_name='statlv',
        ),
    ]
