# Generated by Django 4.0.8 on 2023-01-01 06:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_statlv_joinedlink_statlv'),
    ]

    operations = [
        migrations.CreateModel(
            name='moct_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('fnode_id', models.BigIntegerField()),
            ],
        ),
    ]
