# Generated by Django 4.0.8 on 2023-01-01 07:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_moct_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moct_links',
            name='location',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
        ),
    ]
