# Generated by Django 4.0.8 on 2023-01-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_moct_links_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='moct_links',
            name='fnode_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moct_links',
            name='fnode_id',
            field=models.CharField(max_length=255),
        ),
    ]
