# Generated by Django 4.0.8 on 2023-01-05 11:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_moct_links_fnode_name_alter_moct_links_fnode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moct_links',
            name='location',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=4326),
        ),
    ]
