# Generated by Django 4.0.8 on 2023-01-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_res_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='res_links',
            name='min_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='res_links',
            name='road_name',
            field=models.CharField(max_length=255),
        ),
    ]
